### ISSUE TITLE
Fix 'redirect to asset' bug in express-gauth

### ISSUE THREAD

**Issue by JaakkoLipsanen** [reaktor/express-gauth#10]
Sometimes when `returnToOriginalUrl` is set to `true`, it doesn't return to the url/website that user accessed but rather some asset (like .js or .css or .png) because... reasons. I think the current theory at Reaktor is that for some reason the `index.html` is cached so when user accesses `/`, the first request that comes to the server is some random asset from `index.html`.

Our internal apps have solved this in their own codebase (see: events, rooms). It should probably be pretty easy to move the logic here into `express-gauth`, but the problem is that this issue is pretty hard to reproduce and thus confirm that it works properly.

**Comment by pihvi** [comment]
It was originally as default that you get redirected there, but as it is like that i.e. really hard to control, it was removed as a default value as that thing just happens all the time. Some kind of caching yes is at least happening as even when you serve new index file that for sure had expired according to the cache headers, browser would still make first a request to the css file found in the old and expired file. So can't see a fully working automation for this problem. Maybe some thingie where you can define non redirectable places e.g. static/css folder or individual assets..

**Comment by JaakkoLipsanen** [comment]
Hmm. The `returnToOriginalUrl` option was added in the last version (#8) so now when that option is used, there's no way around this bug.

One of our internal apps does exactly what you mentioned (makes assets non-redirectable) and also checks that if the request is internal (has referrer and referrer is from same domain) then it won't set that as `session.returnTo`. My understanding is that this has worked succesfully in mitigating those redirect to asset bugs.

```
// Browser might try to fetch assets already before the "main request"
// reaches our server. We must tell apart these locations from where
// the user really tries to go. Also, we should set returnTo only once
// per session.
const rememberInitialUrl = (req, res, next) => {
  const referrer = req.get("referrer");
  const hasSameHost = Boolean(
    referrer && url.parse(referrer).hostname === req.hostname
  );

  const isStaticAsset = /\.(css|jpe?g|gif|ico|js|json|png|svg|woff2?)$/i.test(
    req.originalUrl
  );

  const isInternalRequest = Boolean(hasSameHost || isStaticAsset);
  const sessionSet = Boolean(req.session && req.session.returnTo);

  if (isInternalRequest || sessionSet) return next();

  req.session.returnTo = req.originalUrl;

  return next();
};

app.use(rememberInitialUrl);
...
app.use(gauth)
```

Would it make sense and work if we added the same logic as what is in here to https://github.com/reaktor/express-gauth/blob/master/index.js#L55 ?  `isStaticAsset` logic could also be made overridable with a new field in the options, although I don't know if thats necessary

**Comment by pihvi** [comment]
Sounds like a good idea to try. So would the logic be something like
1. if client has set returnTo url, use that else
2. if the asset is matched with isStaticAsset property return to root / else
3. if original request url is found return there else
4. return to root /

**Comment by JaakkoLipsanen** [comment]
Imo
1. If `req.session.returnTo` is already set OR url is matched with isStaticAsset OR url is an internal request, then don't do anything.
2. Otherwise set `req.session.returnTo = req.originalUrl`
3. In the end after gauth, we return to `req.session.returnTo || '/'`, so if returnTo isn't set to anything it defaults to root.

I can do a PR, lets see how it looks
