### ISSUE TITLE
Add stripping of url parameters to the publicEndPoints validation

### ISSUE THREAD

**Issue by ikkala** [reaktor/express-gauth#19]
In Rooms pull request https://github.com/reaktor/rooms/pull/332 "Add radiator options for non-HQ office needs" new URL parameters were added to support cases where Rooms radiator view is used to show just one specific meeting room. This works fine when already authenticated but when radiator view is opened originally, it authenticates by calling the following Express.js [router path](https://github.com/reaktor/rooms/blob/master/src-backend/passport.ts#L46):
```
app.get("/auth/radiator/:secret", ...
```
and after successful authentication the query parameters are passed forward to browser redirect:
```
res.redirect(`/radiator.html?radiatorSecret=${req.params.secret}&${optionalQueryParams}`)
```
Now, in case of optinal parameters, the access to the auth path is failing because [the paths](https://github.com/reaktor/rooms/blob/5268eadbafa58fd8aa99c5a6f3502854bf9dd997/src-backend/passport.ts#L35)
```
publicEndPoints: [`/auth/radiator/${process.env.RADIATOR_SECRET}`, "/logout"],
```
given to [https://github.com/reaktor/express-gauth](https://github.com/reaktor/express-gauth) are validated strictly without stripping the url parameters away.

Based on [a quick search](https://github.com/search?q=org%3Areaktor%20publicEndPoints&type=code) to Reaktor repositories, the `publicEndPoints` feature is used only in [Google Contacts sync](https://github.com/reaktor/google-contacts-sync/blob/d7e2c0aaec791b2214d01860a1270ef001a469ea/src/middleware/authentication.ts#L70) and in [Rooms](https://github.com/reaktor/rooms/blob/5268eadbafa58fd8aa99c5a6f3502854bf9dd997/src-backend/passport.ts#L35), so adding the stripping of url parameters wouldn't affect too many existing systems.

**Comment by rjoonas** [comment]
Fun to hear that Google Contacts sync is still in use!
