### ISSUE TITLE
Email parsing does not follow RFC 822

### ISSUE THREAD

**Issue by rjoonas** [reaktor/express-gauth#2]
[The library's current email parsing algorithm](https://github.com/reaktor/express-gauth/blob/8d0c83a0a2aec928c211a9d315e7cf361ae2ca93/index.js#L76) is naive and will fail for some valid email addresses.

According to [RFC 822](https://tools.ietf.org/html/rfc822#section-3.3) an email address can contain  any number of (quoted) `@` symbols so parsing everything after the first `@` as the domain can yield incorrect results.

**Comment by pihvi** [comment]
Solved? https://github.com/reaktor/express-gauth/commit/f9928dc182c9f1f72e3e1a202ba5b396ef1f6145
